#!/bin/bash

cd $(dirname $0)

mkdir -p bin; pushd bin

cat <<EOF > uninstall-mac
#!/bin/bash

ps aux | grep "php -S 127.0.0.1:8080" | grep -v "grep" | awk '{print \$2}' | xargs kill
ps aux | grep "tsc" | grep -v "grep" | awk '{print \$2}' | xargs kill
cd \$(dirname \$0)/..
rm -rf dist node_modules bin etc *.json
EOF
chmod +x uninstall-mac

cat <<EOF > localServer8080
#!/bin/bash

cd \$(dirname \$0)/..
php -S 127.0.0.1:8080
EOF
chmod +x localServer8080

cat <<EOF > tsc-restart
#!/bin/bash
tsc -w -p \$(dirname \$0)/../etc
EOF
chmod +x tsc-restart

cat <<EOF > run-all
#!/bin/bash

cd \$(dirname \$0)
open -a Terminal.app tsc-restart && open -a Terminal.app localServer8080 && sleep 3 && open -a Terminal.app run-unit-test && open -a Google\ Chrome.app http://127.0.0.1:8080/index.html
EOF
chmod +x run-all

cat <<EOF > run-unit-test
#!/bin/bash

cd \$(dirname \$0)
open -a Terminal.app localServer8080 && sleep 3 && open -a Google\ Chrome.app http://127.0.0.1:8080/unit-test/index.html
EOF
chmod +x run-unit-test

popd

# Create typescript configuration file
mkdir -p etc
cat <<EOF > etc/tsconfig.json
{
  "include": ["../src"],
  "compilerOptions": {
    "target": "es6",
	  "outDir": "../dist",
    "rootDirs": ["../src/"],
	  "strict": true
  }
}
EOF

cat <<EOF > package.json
{
  "name": "template",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "lib": ""
  },
  "keywords": [],
  "author": "Antonio Astorino",
  "license": "ISC",
  "repository": "https://github.com/antonioastorino/WebGL.git"
}
EOF