#!/bin/bash

cd $(dirname $0)

mkdir -p scripts; pushd scripts

cat <<EOF > uninstall-mac
#!/bin/bash

ps aux | grep "php -S 127.0.0.1:808" | grep -v "grep" | awk '{print \$2}' | xargs kill
cd \$(dirname \$0)/..
rm -rf dist node_modules scripts *.json
EOF
chmod +x uninstall-mac

cat <<EOF > localServer8080
#!/bin/bash

cd \$(dirname \$0)/..
php -S 127.0.0.1:8080
EOF
chmod +x localServer8080

cat <<EOF > localServer8081
#!/bin/bash

cd \$(dirname \$0)/..
php -S 127.0.0.1:8081
EOF
chmod +x localServer8081

cat <<EOF > tsc-restart
#!/bin/bash

cd \$(dirname \$0)/..
tsc -w
EOF
chmod +x tsc-restart

cat <<EOF > run-all
#!/bin/bash

cd \$(dirname \$0)
open -a Terminal.app tsc-restart && open -a Terminal.app localServer8080 && sleep 3 && open -a Terminal.app run-unit-test && open -a Google\ Chrome.app http://127.0.0.1:8080/index.html
EOF
chmod +x run-all

cat <<EOF > run-unit-test
#!/bin/bash

cd \$(dirname \$0)
open -a Terminal.app localServer8081 && sleep 3 && open -a Google\ Chrome.app http://127.0.0.1:8081/unit-test/index.html
EOF
chmod +x run-unit-test

popd

# Create typescript configuration file
cat <<EOF > tsconfig.json
{
  "include": ["../"],
  "compilerOptions": {
    "target": "es6",
	"outDir": "./dist",
    "rootDirs": ["./src", "./lib"],
	"strict": true,
	"typeRoots": [ "/usr/local/lib/node_modules/types" ],
    "types": [ "jquery" ],
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true
  }
}
EOF

cat <<EOF > package.json
{
  "name": "template",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "directories": {
    "lib": ""
  },
  "scripts": {
    "test": "jasmine"
  },
  "keywords": [],
  "author": "Antonio Astorino",
  "license": "ISC"
}
EOF

npm install --save @types/jquery
